"""
IRA Daily Briefing Generator.

Produces a rich morning briefing covering:
  - Business overview (leads, bookings, revenue pipeline)
  - Security status (threats, blocked IPs, system health)
  - Calendar (today's meetings and calls)
  - Tasks (pending, overdue, due today)
  - Proactive suggestions (things IRA noticed that need attention)

The briefing text is generated by the fast LLM from structured DB data,
then delivered via all configured channels.

Schedule: Daily at 08:00 (configurable via BRIEFING_SCHEDULE env var)
Also triggered: on demand via POST /api/v1/briefing/now
"""

from __future__ import annotations

import asyncio  # Fix L9: moved from inside _gather_all() — function-local imports shadow module scope and confuse static analysis tools
import json
import logging
import uuid
from datetime import datetime, timezone, timedelta
from zoneinfo import ZoneInfo

from utils.db import acquire
from utils.llm import chat_complete
from worker.notifier import notify

logger = logging.getLogger("ira.briefing")

# ── Data gathering ─────────────────────────────────────────────────────────────

async def _gather_business_data() -> dict:
    """Pull business metrics for the last 24 hours."""
    async with acquire() as conn:
        leads_today = await conn.fetchval(
            "SELECT COUNT(*) FROM business_events WHERE event_type='lead' AND created_at > NOW() - INTERVAL '24 hours'"
        )
        bookings_today = await conn.fetchval(
            "SELECT COUNT(*) FROM business_events WHERE event_type='booking' AND created_at > NOW() - INTERVAL '24 hours'"
        )
        total_leads_week = await conn.fetchval(
            "SELECT COUNT(*) FROM business_events WHERE event_type='lead' AND created_at > NOW() - INTERVAL '7 days'"
        )
        recent_leads = await conn.fetch(
            """SELECT title, status, created_at, payload
               FROM business_events WHERE event_type='lead'
               ORDER BY created_at DESC LIMIT 5"""
        )
    return {
        "leads_24h": leads_today or 0,
        "bookings_24h": bookings_today or 0,
        "leads_7d": total_leads_week or 0,
        "recent_leads": [
            {"title": r["title"], "status": r["status"]}
            for r in recent_leads
        ],
    }


async def _gather_security_data() -> dict:
    """Pull security status."""
    async with acquire() as conn:
        critical = await conn.fetchval(
            "SELECT COUNT(*) FROM security_events WHERE severity IN ('critical','high') AND resolved=FALSE"
        )
        total_unresolved = await conn.fetchval(
            "SELECT COUNT(*) FROM security_events WHERE resolved=FALSE"
        )
        last_events = await conn.fetch(
            """SELECT severity, event_type, description, created_at
               FROM security_events WHERE resolved=FALSE
               ORDER BY created_at DESC LIMIT 3"""
        )
    return {
        "critical_unresolved": critical or 0,
        "total_unresolved": total_unresolved or 0,
        "recent_threats": [
            {"severity": r["severity"], "type": r["event_type"], "desc": r["description"][:80]}
            for r in last_events
        ],
    }


async def _gather_tasks_data() -> dict:
    """Pull tasks due today and overdue."""
    async with acquire() as conn:
        overdue = await conn.fetchval(
            "SELECT COUNT(*) FROM tasks WHERE status='pending' AND due_at < NOW()"
        )
        due_today = await conn.fetch(
            """SELECT title, priority, due_at FROM tasks
               WHERE status IN ('pending','in_progress')
               AND due_at BETWEEN NOW() AND NOW() + INTERVAL '24 hours'
               ORDER BY due_at ASC LIMIT 10"""
        )
        pending_urgent = await conn.fetchval(
            "SELECT COUNT(*) FROM tasks WHERE status='pending' AND priority='urgent'"
        )
    return {
        "overdue": overdue or 0,
        "urgent_pending": pending_urgent or 0,
        "due_today": [
            {"title": r["title"], "priority": r["priority"]}
            for r in due_today
        ],
    }


async def _gather_calendar_data() -> dict:
    """Pull today's calendar events using the owner's local timezone."""
    from config import get_settings
    _cfg = get_settings()
    tz = ZoneInfo(getattr(_cfg, "briefing_timezone", "UTC"))
    _today = datetime.now(tz).date()
    today_end = datetime(_today.year, _today.month, _today.day, 23, 59, 59, tzinfo=tz)
    async with acquire() as conn:
        events = await conn.fetch(
            """SELECT title, start_at, end_at, location, attendees
               FROM calendar_events
               WHERE start_at BETWEEN NOW() AND $1 AND status='confirmed'
               ORDER BY start_at ASC""",
            today_end,
        )
    return {
        "meetings_today": len(events),
        "events": [
            {
                "title": r["title"],
                "time": r["start_at"].strftime("%H:%M"),
                "location": r["location"] or "Virtual",
            }
            for r in events
        ],
    }


# ── Briefing generation ────────────────────────────────────────────────────────

_BRIEFING_PROMPT = """\
You are IRA — a warm, professional Indian female AI executive assistant.
Generate a morning briefing for Sir based on the data below.

Tone: Professional, warm, proactive. Use "Sir" naturally. Be concise but complete.
Format: Use clear sections with emoji headers. End with 1-2 proactive suggestions.

Data:
{data}

Generate the briefing now. Make it feel like a real executive assistant speaking,
not a data dump. Highlight anything urgent. Keep it under 400 words.\
"""


async def generate_briefing(briefing_type: str = "morning") -> str:
    """Generate and deliver a briefing. Returns the briefing text."""
    logger.info(f"Generating {briefing_type} briefing...")

    business, security, tasks, calendar = await _gather_all()

    now = datetime.now(timezone.utc)
    data_summary = {
        "date": now.strftime("%A, %d %B %Y"),
        "time": now.strftime("%H:%M UTC"),
        "business": business,
        "security": security,
        "tasks": tasks,
        "calendar": calendar,
    }

    messages = [
        {"role": "system", "content": _BRIEFING_PROMPT.format(
            data=json.dumps(data_summary, indent=2)
        )},
        {"role": "user", "content": f"Please give me my {briefing_type} briefing."},
    ]

    briefing_text = await chat_complete(messages, use_deep=False, temperature=0.6, max_tokens=600)

    # Persist
    briefing_id = str(uuid.uuid4())
    async with acquire() as conn:
        await conn.execute(
            """INSERT INTO briefings (id, briefing_type, content, data, delivered)
               VALUES ($1, $2, $3, $4, TRUE)""",
            uuid.UUID(briefing_id), briefing_type, briefing_text,
            json.dumps(data_summary),
        )
        await conn.execute(
            "UPDATE monitor_state SET value=$1, updated_at=NOW() WHERE key='last_briefing_sent'",
            now.isoformat(),
        )

    # Deliver via all configured channels
    priority = "critical" if security["critical_unresolved"] > 0 else "info"
    await notify(
        f"IRA {briefing_type.title()} Briefing — {now.strftime('%d %b')}",
        briefing_text,
        category="briefing",
        priority=priority,
        metadata={"briefing_id": briefing_id, "type": briefing_type},
    )

    logger.info(f"Briefing delivered. {len(briefing_text)} chars.")
    return briefing_text


async def _gather_all() -> tuple[dict, dict, dict, dict]:
    return await asyncio.gather(
        _gather_business_data(),
        _gather_security_data(),
        _gather_tasks_data(),
        _gather_calendar_data(),
    )
